Algoritmo "semnome"
/// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/11/2022
Var
// Seção de Declarações das variáveis 
x: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 enquanto x<1000 faca
 x<-x+2
 escreva (x)
 
 fimenquanto

Fimalgoritmo