Algoritmo "semnome"

Var
x1: inteiro

Inicio
para x1 de 1 ate 5 faca
ESCREVAL("===DIGITE UM NUMERO PARA VER SUA TABUADA===")
leia(x1)
escreval(x1," x 1 =", x1 * 1)
escreval(x1," x 2 =",x1 * 2)
escreval(x1," x 3 =",x1 * 3)
escreval(x1," x 4 =",x1 * 4)
escreval(x1," x 5 =",x1 * 5)
escreval(x1," x 6 =",x1 * 6)
escreval(x1," x 7 =",x1 * 7)
escreval(x1," x 8 =",x1 * 8)
escreval(x1," x 9 =",x1 * 9)
escreval(x1," x 10 =",x1 * 10)
fimpara
Fimalgoritmo